# Python Introduction:
---

## Types

Let's evaluate some simple expressions.

In [1]:
3*2

6

In [2]:
5+3*2

11

You can use `type()` to find the *type* of an expression.

In [3]:
type(5)

int

Now add decimal points.

In [4]:
5+3.5*2

12.0

In [5]:
type(5+3.0*2)

float

Strings are written with single (``'``) or double quotes (`"`)

In [6]:
'hello "hello"'

"hello 'hello'"

"hello 'hello'"

Multiplication and addition work on strings, too.

In [7]:
3 * 'hello ' + "cs357"

'hello hello hello cs357'

Lists are written in brackets (`[]`) with commas (`,`).

In [8]:
[5, 3.5, 7]

[5, 3.5, 7]

Check the type of the above list:

In [9]:
type([5,3.5,7])

list

List entries don't have to have the same type.

In [10]:
["hi there", 15, [1,2,3]]

['hi there', 15, [1, 2, 3]]

"Multiplication" and "addition" work on lists, too. Try this:
```
[1,2,3] * 4 + [5, 5, 5]
```

In [11]:
[1,2,3] * 4 + [5, 5, 5]

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 5, 5, 5]

Hmmmmmm. Was that what you expected? How can we "fix" this?

In [12]:
import numpy as np

np.array([1,2,3]) * 4 + np.array([5,5,5])

array([ 9, 13, 17])

We will introduce python later in this notebook

## Names and Values

Define and reference a variable:

In [15]:
a = 3*2 + 5
a

11

In [16]:
a = "interesting"*3
a

'interestinginterestinginteresting'

No type declaration needed!

(But values still have types--let's check.)

In [17]:
type(a)

str

Everything in python is an object. Python variables are like *pointers*.

(if that word makes sense)

In [18]:
a = [1,2,3]

In [19]:
b = a

In [29]:
print(a)
print(b)
print(a==b)

[1, 2, 3]
[1, 2, 3]
True


In [23]:
b.append(4)

In [24]:
b

[1, 2, 3, 4]

In [25]:
a

[1, 2, 3, 4]

You can see this pointer with `id()`.  Check the id of the variables `a` and `b`:

In [26]:
id(b)

4458649024

The `is` operator tests for object sameness.

In [27]:
a is b

True

This is a **stronger** condition than being equal!

In [28]:
a = [1,2,3]
b = [1,2,3]
print("IS   ", a is b)
print("EQUAL", a == b)

IS    False
EQUAL True


What do you think the following prints?

In [30]:
a = [1,2,3]
b = a
a = a + [4]
print(b)
print(a)

[1, 2, 3]
[1, 2, 3, 4]


In [32]:
a is b

False

Why is that?

<details>
<summary>Addition</summary>
Because when we do + operation on two lists, we are creating a new list and assigning it to a. 
<details>

-----
How could this lead to bugs?

----------
* To help manage this risk, Python provides **immutable** types.

* Immutable types cannot be changed in-place, only by creating a new object.

* A `tuple` is an immutable `list`.

In [26]:
a = [1,2,3]
type(a)

list

In [27]:
a[2] = 0
print(a)

[1, 2, 0]


In [33]:
a = (1,2,3)
type(a)

tuple

Let's try to change that tuple. Modify only one entry of the tuple and see what happens.

In [34]:
# clear
a[2] = 0

TypeError: 'tuple' object does not support item assignment

How do you spell a single-element tuple?

In [35]:
a = (3,)

type(a)

tuple

String is also immutable type. 

In [36]:
myName = 'Mariena'

Note that myName is spelled incorrectly. We would like to change the letter "e" with a letter "a"

In [37]:
myName[4]

'e'

What happens if we try to "fix" this as follows?

In [38]:
myName[4]='a'

TypeError: 'str' object does not support item assignment

## Memory management

In [39]:
a = "apple"
b = "apple"
print(id(a),id(b))
print (a is b)
print (a == b)

4453903712 4453903712
True
True


<img src="PointToString.png" width=200 />

Note that "a" and "b" are bounded to the same object "apple", and therefore they have the same id. For optimization reasons, Python does not store duplicates of "simple" strings. But if the strings are a little more complicated...

In [40]:
a = "Hello, how are you?"
b = "Hello, how are you?"
print(id(a),id(b))
print (a is b)
print (a == b)

4461512240 4461511280
False
True


This is called interning, and Python does interning (to some extent) of shorter string literals (such as "apple") which are created at compile time. But in general, Python string literals creates a new string object each time (as in "Hello, how are you?"). Interning is runtime dependant and is always a trade-off between memory use and the cost of checking if you are creating the same string. 

In general, integers, floats, lists, tuples, etc, will be stored at different locations, and therefore have different ids.

In [41]:
a = 5000
b = 5000
print(id(a),id(b))
print (a is b)
print (a == b)

4459736912 4459734288
False
True


In [42]:
a = (1,[2,3],4)
b = (1,[2,3],4)
print(id(a),id(b))
print (a is b)
print (a == b)

4461191680 4461191616
False
True


Also for optimization reasons, Python will <strong>not</strong> duplicate integers between -5 and 256. Instead, it will  keep an array of integer objects for all integers between -5 and 256, so when you create an int in that range you actually just get back a reference to the existing object. 

In [43]:
a = 256
b = 256
print(id(a),id(b))
print (a is b)
print (a == b)

4357671320 4357671320
True
True


In [44]:
a = 257
b = 257
print(id(a),id(b))
print (a is b)
print (a == b)

4459737232 4459737360
False
True


## Objects and Naming

Understanding objects and naming in Python can be difficult.  In this demo we'll follow a post [Is Python call-by-value or call-by-reference? Neither.](https://jeffknupp.com/blog/2012/11/13/is-python-callbyvalue-or-callbyreference-neither/).

First, let's make some objects.  *Everything in Python is an object*.

In [ ]:
#So when we make a string it's an object. When we call it a variable name, it binds that name to the string object. 
fruit = 'apple'

#When we make a list, it will point to the object bound by fruit
lunch = []
lunch.append(fruit)
# lunch is now ['apple']

dinner = lunch
dinner.append('fish')
# dinner is now ['apple', 'fish']
# lunch is now ['apple', 'fish'] as well
fruit = 'pear'

meals = [fruit, lunch, dinner]
print(meals)



['pear', ['apple', 'fish'], ['apple', 'fish']]


Let's check the object ids for both lists

In [46]:
print(id(lunch))
print(id(dinner))

4460830976
4460830976


Notice what happens when we append to list that is bound to both `lunch` and `dinner`:

In [47]:
dinner.append('pasta')
print(lunch, dinner)

['apple', 'fish', 'pasta'] ['apple', 'fish', 'pasta']


In [48]:
lunch.append('carrots')
print(lunch,dinner)

['apple', 'fish', 'pasta', 'carrots'] ['apple', 'fish', 'pasta', 'carrots']


## Mutable and Immutable

We've looked at mutable and immutable.  Tuples are an example of immutable objects.

In [49]:
fruits = ['apple', 'banana', 'orange']
veggies = ['carrot', 'broccoli']

food_tuple = (fruits, veggies)


fruits.append('plum')

print(fruits)

print(food_tuple)


['apple', 'banana', 'orange', 'plum']
(['apple', 'banana', 'orange', 'plum'], ['carrot', 'broccoli'])


## Indexing and Slicing

The `range` function lets us build a list of numbers.

In [50]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
list(range(10, 20,1))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Notice anything funny?

Python uses this convention everywhere.

In [52]:
a = list(range(10, 20))
type(a)

list

Let's talk about indexing.

Indexing in Python starts at 0.

In [53]:
a[0]

10

And goes from there.

In [54]:
a[1]

11

In [42]:
a[2]

12

What do negative numbers do?

In [55]:
a[-1]

19

In [56]:
a[-2]

18

You can get a sub-list by *slicing*.

In [57]:
print(a)
print(a[3:7])

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[13, 14, 15, 16]


Start and end are optional.

In [58]:
a[3:]

[13, 14, 15, 16, 17, 18, 19]

In [59]:
a[:3]

[10, 11, 12]

Again, notice how the end entry is not included:

In [60]:
print(a[:3])
print(a[3])

[10, 11, 12]
13


Slicing works on any sequence type! (`list`, `tuple`, `str`, `numpy` array)

In [61]:
a = "CS357"
a[-3:]

'357'

In [62]:
a = [0,1,2,3,4,5,6,7,8,9]
a[1::2][::-1]

[9, 7, 5, 3, 1]

## Control Flow

`for` loops in Python always iterate over something list-like:

In [63]:
for i in range(3,10):

    print(i)
    

3
4
5
6
7
8
9


**Note** that Python does block-structuring by leading spaces.

Also note the trailing "`:`".

---
`if`/`else` are as you would expect them to be:

In [64]:
for i in range(10):
    if i % 3 == 0:
        print("{0} is divisible by 3".format(i))
    else:
        print("{0} is not divisible by 3".format(i))

0 is divisible by 3
1 is not divisible by 3
2 is not divisible by 3
3 is divisible by 3
4 is not divisible by 3
5 is not divisible by 3
6 is divisible by 3
7 is not divisible by 3
8 is not divisible by 3
9 is divisible by 3


In [65]:
print("My name is %s" % 'Luke')
print("My name is {}".format('Luke'))

My name is Luke
My name is Luke


`while` loops exist too:

In [66]:
i = 0
while True:
    i += 1
    if i**3 + i**2 + i + 1 == 3616:
        break

print("SOLUTION:", i)

SOLUTION: 15


----
Building lists by hand can be a little long. For example, build a list of the squares of integers below 50 divisible by 7:

In [67]:
mylist = []

for i in range(50):

    if i % 7 == 0:

        mylist.append(i**2)

In [56]:
mylist

[0, 49, 196, 441, 784, 1225, 1764, 2401]

Python has a something called *list comprehension*:

In [68]:
mylist = [i**2 for i in range(50) if i % 7 == 0]
print(mylist)

[0, 49, 196, 441, 784, 1225, 1764, 2401]


## Enumerate

suppose you had a single list:

In [69]:
fruits = ['apples', 'bananas', 'oranges', 'grapes']
for i, f in enumerate(fruits):
    print("%d: the fruit is %s" % (i,f))

0: the fruit is apples
1: the fruit is bananas
2: the fruit is oranges
3: the fruit is grapes


## Zip (another helpful function)

In [70]:
ids = ['a', 'b', 'c', 'd']
fruits = ['apples', 'bananas', 'oranges', 'grapes']
for c in zip(ids, fruits):
    print(c)

('a', 'apples')
('b', 'bananas')
('c', 'oranges')
('d', 'grapes')


## Dictionaries

Dictionaries have *key*:*value* pairs of any Python object:

In [71]:
#mydict = {key: value}
mydict = {'Luke': 15,'Mariana' : 22}
print(mydict["Mariana"])

22


In [72]:
string = "Batman"
mydict = {key:ord(key) for key in string}

In [73]:
print(mydict)

{'B': 66, 'a': 97, 't': 116, 'm': 109, 'n': 110}


## Function definitions


Functions help extract out common code blocks.

Let's define a function `print_greeting()`.

In [74]:
def print_greeting():
    print("Hi there, how are you?")
    print("Long time no see.")

And call it:

In [75]:
print_greeting()

Hi there, how are you?
Long time no see.


That's a bit impersonal.

In [76]:
def print_greeting(name):

    print("Hi there, {0}, how are you?".format(name))

    print("Long time no see.")

In [78]:
print_greeting("Andreas")

Hi there, Andreas, how are you?
Long time no see.


In [79]:
print_greeting()

TypeError: print_greeting() missing 1 required positional argument: 'name'

But we might not know their name. So we can set a default value for parameters.

(And we just changed the interface of `print_greeting`!)

In [80]:
def print_greeting(name="my friend"):

    print("Hi there, {0}, how are you?".format(name))

    print("Long time no see.")

In [81]:
print_greeting("Tim")

Hi there, Tim, how are you?
Long time no see.


Note that the order of the parameters does not matter

In [82]:
def printinfo( name , age ):
    print("Name: ", name)
    print("Age: ", age)

printinfo(40,"Mariana")


Name:  40
Age:  Mariana


In [83]:
printinfo( age=8, name="Julia" )

Name:  Julia
Age:  8


However the parameters "age" and "name" are both required above. What if we want to have optional parameters (without setting default values)?

In [84]:
def printinfo( firstvar , *othervar ):
    print("First parameter:", firstvar)
    print("List of other parameters:")
    for var in othervar:
        print(var)

# Now you can call printinfo function
printinfo(10,20,30,50,60)


First parameter: 10
List of other parameters:
20
30
50
60


## Packing and Unpacking

In [85]:
def give_me_fruits():
    return ['apple', 'banana', 'orange', 'plum']

In [86]:
*myfruits, _ = give_me_fruits()
print(myfruits)

['apple', 'banana', 'orange']


Above we used `_` to denote a return that we want to just ignore (and not bind to a name).

In [87]:
def some_fruits(fruit, *morefruits):
    print('The best fruit is %s' % fruit)
    for f in morefruits:
        print('...not %s' % f)

In [88]:
some_fruits('apple', 'banana', 'orange', 'plum')

The best fruit is apple
...not banana
...not orange
...not plum


A function can also return more than one parameter, and the results appear as a tuple:

In [89]:
def average_total(a,b):
    totalsum = a + b
    average = totalsum/2
    diff = a - b
    return average,totalsum, diff

#We can unpack values returned from a function
ave,tot,diff = average_total(3,5)
print(ave, tot, diff)

#We can unpack values using the star mark (*) for variable length
ave, *othervar, diff = average_total(3,5)
print(ave, diff)

ave, *_ = average_total(3,5)
print(ave)

4.0 8 -2
4.0 -2
4.0


## Remember mutable and immutable types...

Function parameters work like variables. So what does this do?

In [94]:
def my_func(my_list):
    my_list.append(5)
    print("List printed inside the function: ",my_list)
    
numberlist = [1,2,3]
print("List before function call: ",numberlist)
my_func(numberlist)
print("List after function call: ",numberlist)

List before function call:  [1, 2, 3]
List printed inside the function:  [1, 2, 3, 5]
List after function call:  [1, 2, 3, 5]


Can be very surprising! Here, we are maintaining reference of the passed object and appending values in the same object.

Define a better function `my_func_2`:

In [95]:
def my_func_2(my_list):
    
    my_list = my_list + [5]
    print("List printed inside the function: ",my_list)

    return my_list


numberlist = [1,2,3]
print("List before function call: ",numberlist)
new_list = my_func_2(numberlist)
#inside the function my_list = [1,2,3,5]
print("List after function call: ",numberlist)
print("Modified list after function call: ",new_list)

List before function call:  [1, 2, 3]
List printed inside the function:  [1, 2, 3, 5]
List after function call:  [1, 2, 3]
Modified list after function call:  [1, 2, 3, 5]


Note that the parameter my_list is local to the function. 

In [96]:
def change_fruits(fruit):
    fruit='apple'
    print("I'm changing the fruit to %s" % fruit)

In [97]:
myfruit = 'banana'
change_fruits(myfruit)
print("The fruit is %s " % myfruit)

I'm changing the fruit to apple
The fruit is banana 


**What happened?!** Remember that the input, `fruit` to `change_fruits` is bound to an object within the scope of the function:
  * If the object is mutable, the object will change
  * If the object is immutable (like a string!), then a new object is formed, only to live within the function scope.

## Try to answer before running the code snippet

In [98]:
def add_minor(person):
    person.append('math')

def switch_majors(person):
    person = ['physics']
    person.append('economics')
    return(person)


In [99]:
# What are the values of Tim and John?
John = ['computer_science']
Tim = John
print(Tim,John)
print(Tim is John)

['computer_science'] ['computer_science']
True


In [100]:
# What are the values of Tim and John?
add_minor(Tim)
print(Tim,John)

['computer_science', 'math'] ['computer_science', 'math']


In [101]:
# What are the values of Tim and John?
switch_majors(John)
print(Tim,John)

['computer_science', 'math'] ['computer_science', 'math']


# Numpy Introduction:
---

## A Difference in Speed

Let's import the `numpy` module.

In [102]:
import numpy as np

In [103]:
n = 5  # CHANGE ME
a1 = list(range(n)) # python list
a2 = np.arange(n)   # numpy array

if n <= 10:
    print(a1)
    print(a2)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [107]:
%timeit [i**2 for i in a1]

119 ns ± 1.05 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [106]:
%timeit a2**2

195 ns ± 2.47 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


Numpy Arrays: much less flexible, but:

* much faster
* less memory

## Creating a numpy array

* Casting from a list

In [108]:
a = np.array([1,2,3,5])
print(a)
print(type(a))
print(a.dtype)

[1 2 3 5]
<class 'numpy.ndarray'>
int64


In [109]:
b = np.array([1.0,2.0,3.0])
print(b)
print(b.dtype)

[1. 2. 3.]
float64


But also noticed that:

In [110]:
c = np.array([1,2,3])
print(c)
print(c.dtype)

d = np.array([1,2.,3])
print(d)
print(d.dtype)

[1 2 3]
int64
[1. 2. 3.]
float64


* `linspace`
* np.linspace(start, stop, num=50,...)
* num is the number of sample points

In [111]:
np.linspace(-1, 1, 9)

array([-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ])

* `zeros`

In [112]:
np.zeros((10,10), np.float64)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Create 2D arrays, using zeros, using reshape and from list

## Operations on arrays

These propagate to all elements:

In [113]:
a = np.array([1.2, 3, 4])
b = np.array([0.5, 0, 1])

Addition, multiplication, power ... are all elementwise:

In [114]:
a+b

array([1.7, 3. , 5. ])

In [115]:
a*b

array([0.6, 0. , 4. ])

In [84]:
a**b

array([1.09544512, 1.        , 4.        ])

## Important Attributes

Numpy arrays have two (most) important attributes:

In [116]:
A = np.random.rand(5, 4, 3)
A.shape
A

array([[[0.16527434, 0.80800813, 0.96855716],
        [0.80812491, 0.97480501, 0.70871519],
        [0.90182111, 0.54113141, 0.40260999],
        [0.38925167, 0.09309013, 0.82555222]],

       [[0.29354824, 0.37445419, 0.77874647],
        [0.04031296, 0.67595697, 0.35245415],
        [0.14038375, 0.5125669 , 0.23442268],
        [0.59488858, 0.76979704, 0.65247092]],

       [[0.45540164, 0.25699472, 0.21381395],
        [0.46447524, 0.32521926, 0.41630554],
        [0.99731474, 0.78935138, 0.1062407 ],
        [0.25919177, 0.6349974 , 0.52547763]],

       [[0.23053028, 0.33842277, 0.63400475],
        [0.68257863, 0.9619491 , 0.64939725],
        [0.61831204, 0.74191138, 0.68864961],
        [0.44170314, 0.82379741, 0.30175564]],

       [[0.65254332, 0.20348777, 0.46677598],
        [0.65715826, 0.07910077, 0.92164357],
        [0.61039388, 0.1494957 , 0.89328898],
        [0.53653477, 0.39066855, 0.78572945]]])

The `.shape` attribute contains the dimensionality array as a tuple. So the tuple `(5,4,3)` means that we're dealing with a three-dimensional array of size $5 \times 4 \times 3$.

(`numpy.random.rand` just generates an array of random numbers of the given shape.)

In [117]:
A.dtype

dtype('float64')

Other `dtype`s include `np.complex64`, `np.int32`, ...

## Try to answer before running the code snippet

In [118]:
a = np.array([2,2,3])
b = np.array([1,3,2])

# What is the result of the following computation?
c = (a+b)*a**b

In [119]:
print(c)

[ 6 40 45]


## 1D arrays

In [120]:
a = np.random.rand(5)
a.shape

(5,)

In [121]:
a = np.array([2,3,5])
print(a)
print(a.shape)

[2 3 5]
(3,)


## 2D arrays

In [122]:
a = np.array([[2],[3],[5]])
print(a)
print(a.shape)

a = np.array([[2,3,5]])
print(a)
print(a.shape)

[[2]
 [3]
 [5]]
(3, 1)
[[2 3 5]]
(1, 3)


We can change 1D numpy arrays into 2D numpy arrays using the function `reshape`

In [95]:
a = np.array([2,3,5]).reshape(3,1)
print(a)
print(a.shape)

[[2]
 [3]
 [5]]
(3, 1)


In [123]:
a = np.array([2,3,5]).reshape(1,3)
print(a)
print(a.shape)

[[2 3 5]]
(1, 3)


In [124]:
print(np.arange(1,10))
B = np.arange(1,10).reshape(3,3)
print(B)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose

In [125]:
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [126]:
print(B.transpose())
print(B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [127]:
print(B.swapaxes(0,1))
print(B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [128]:
print(B.T)
print(B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [129]:
C = np.transpose(B)
print(C)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


What happens when we try to take the transpose of 1D array?

In [130]:
a = np.array([[2,3,5]])
print(a.T)

[[2]
 [3]
 [5]]


But it works with 2D arrays

In [131]:
a = np.array([2,3,5]).reshape(3,1)
print(a)
print(a.T)

[[2]
 [3]
 [5]]
[[2 3 5]]


## Inner and outer products

Matrix multiplication is `np.dot(A, B)` for two 2D arrays.

In [132]:
A = np.random.rand(3, 2)
B = np.random.rand(2, 4)
C = np.dot(A,B)
print(C.shape)

b = np.array([5,6])

d = np.dot(A,b)
print(d.shape)

(3, 4)
(3,)


In [133]:
A = np.array([[1,3],[2,4]])
B = np.array([[2,1],[3,2]])
print(np.dot(A,B))
print(A@B)

[[11  7]
 [16 10]]
[[11  7]
 [16 10]]


In [134]:
a = np.array([1,2,3])
b = np.array([5,6,7])
#Inner Product
print(np.dot(a,b))
print(np.inner(a,b))

38
38


In [135]:
#Outer Product C[i,j] = a[i]*b[j]
C = np.outer(a,b)
print(np.shape(C))
print(C)

(3, 3)
[[ 5  6  7]
 [10 12 14]
 [15 18 21]]


## Try to answer before running the code snippet

In [136]:
A = np.array([[2,1],[1,3]])
B = np.array([[1,3],[2,2]])
c = np.array([[1,2]])
d = np.array([[1],[2]])
c = np.array([1,2])

# What is the output of A@B?

In [139]:
print(np.dot(A,B))
print(A@B)

[[4 8]
 [7 9]]
[[4 8]
 [7 9]]


In [138]:
print(np.dot(A,d))
print(A@c)

[[4]
 [7]]
[4 7]


# numpy: Indexing

In [142]:
A = np.array([[1, 4, 9], [2, 8, 18]])
print(A)

[[ 1  4  9]
 [ 2  8 18]]


In [143]:
A[1,2]

np.int64(18)

What's the result of this?

In [144]:
A[:,1]

array([4, 8])

And this?

In [145]:
A[1:,:1]

array([[2]])

One more:

In [146]:
A[:,[0,2]]

array([[ 1,  9],
       [ 2, 18]])

## Try to answer before running the code snippet

In [147]:
myList = [1,2,3,4,5,6.5]
print(type(myList[0]))

<class 'int'>


In [148]:
vec1 = np.array(myList)
# What is the type of vec1[0]?

In [149]:
print(type(vec1[0]))

<class 'numpy.float64'>


In [150]:
A = np.array([[1, 4, 9, 3], [2, 8, 3, 18], [4, 5, 1, 2], [6, 4, 6, 3]])
print(A)
print(A[1:2,2:])

[[ 1  4  9  3]
 [ 2  8  3 18]
 [ 4  5  1  2]
 [ 6  4  6  3]]
[[ 3 18]]


In [151]:
a = np.random.rand(3,4,2)
a.shape

(3, 4, 2)

In [152]:
a[...,1].shape

(3, 4)

---

Indexing into numpy arrays usually results in a so-called *view*.

In [153]:
a = np.zeros((4,4))

Let's call `b` the top-left $2\times 2$ submatrix.

In [154]:
b = a[:2,:2]

What happens if we change `b`?

In [156]:
b[1,0] = 5

In [157]:
a

array([[0., 0., 0., 0.],
       [5., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

To decouple `b` from `a`, use `.copy()`.

In [158]:
b = b.copy()
b[1,1] = 7
print(b)
print(a)

[[0. 0.]
 [5. 7.]]
[[0. 0. 0. 0.]
 [5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Try to answer before running the code snippet

In [136]:
A = np.array([[1, 4, 9, 3], [2, 8, 3, 18], [4, 5, 1, 2], [6, 4, 6, 3]])
b = A[:,2]
print(A)
d = b
print(np.shape(d))
d[2] = 2
print(A)

[[ 1  4  9  3]
 [ 2  8  3 18]
 [ 4  5  1  2]
 [ 6  4  6  3]]
(4,)
[[ 1  4  9  3]
 [ 2  8  3 18]
 [ 4  5  2  2]
 [ 6  4  6  3]]


---

You can also index with boolean arrays:

In [137]:
a = np.random.rand(4,4)

In [138]:
a

array([[0.18549296, 0.39583812, 0.39242453, 0.12197368],
       [0.17679069, 0.07906348, 0.49877055, 0.73692184],
       [0.79133732, 0.83966454, 0.88527927, 0.40955953],
       [0.48994725, 0.91670687, 0.70654034, 0.30608636]])

In [139]:
a_big = a>0.5
a_big

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True, False],
       [False,  True,  True, False]])

In [140]:
a[a_big]

array([0.73692184, 0.79133732, 0.83966454, 0.88527927, 0.91670687,
       0.70654034])

Also each index individually:

In [141]:
a_row_sel = [True, True, False, True]

In [142]:
a[a_row_sel,:]

array([[0.18549296, 0.39583812, 0.39242453, 0.12197368],
       [0.17679069, 0.07906348, 0.49877055, 0.73692184],
       [0.48994725, 0.91670687, 0.70654034, 0.30608636]])

---

And with index arrays:

In [143]:
a

array([[0.18549296, 0.39583812, 0.39242453, 0.12197368],
       [0.17679069, 0.07906348, 0.49877055, 0.73692184],
       [0.79133732, 0.83966454, 0.88527927, 0.40955953],
       [0.48994725, 0.91670687, 0.70654034, 0.30608636]])

In [144]:
x,y = np.nonzero(a > 0.5)

In [145]:
x

array([1, 2, 2, 2, 3, 3])

In [146]:
y

array([3, 0, 1, 2, 1, 2])

In [147]:
a[(x,y)]

array([0.73692184, 0.79133732, 0.83966454, 0.88527927, 0.91670687,
       0.70654034])

# numpy: Broadcasting

In [148]:
import numpy as np

In [149]:
a = np.arange(9).reshape(3,3)
print(a.shape)
print(a)

(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [150]:
b = np.arange(4, 4+9).reshape(3, 3)
print(b.shape)
print(b)

(3, 3)
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [151]:
a+b

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

So this is easy and one-to-one.


---

What if the shapes do not match?

In [152]:
a = np.arange(9).reshape(3, 3)
print(a.shape)
print(a)

(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [153]:
b = np.arange(3)
print(b.shape)
print(b)

(3,)
[0 1 2]


What will this do?

In [154]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

It has *broadcast* along the last axis!

---

Can we broadcast along the *first* axis?

In [156]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [155]:
c = b.reshape(3, 1)
c

array([[0],
       [1],
       [2]])

In [157]:
print(a.shape)
print(c.shape)

(3, 3)
(3, 1)


In [158]:
a+c

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

Rules:

* Shapes are matched axis-by-axis from last to first.
* A length-1 axis can be *broadcast* if necessary.

## Try to answer before running the code snippet

In [160]:
A = np.array([[2,4],[1,3]])
B = np.array([[1,3],[2,2]])
c = np.array([1,2])
print(np.shape(c))

(2,)


In [161]:
print(B + np.dot(A,c))

[[11 10]
 [12  9]]


In [163]:
# broadcasting in both axis:
a = np.arange(1,5)
b = np.arange(3,7)

d = b*a.reshape((4,1))
print(d)
print(np.shape(d))

# note this is the same as the outer product
print(np.outer(a,b))


[[ 3  4  5  6]
 [ 6  8 10 12]
 [ 9 12 15 18]
 [12 16 20 24]]
(4, 4)
[[ 3  4  5  6]
 [ 6  8 10 12]
 [ 9 12 15 18]
 [12 16 20 24]]


## Vectorized computations

In [160]:
def func1(u, v, w):
    n = len(u)
    for i in range(n):
        w[i] = u[i] + 15.2 * v[i]
    
def func2(u, v, w):
    w = u + 15.2 * v


In [161]:
n = 10**7
u = np.random.rand(n)
v = np.random.rand(n)
w = np.zeros(n)


%timeit func1(u,v,w)
%timeit func2(u,v,w)

1.44 s ± 5.84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.36 ms ± 25.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
